export const ciudadesDeChile = [
  'Arica',
  'Iquique',
  'Antofagasta',
  'Copiapó',
  'La Serena',
  'Coquimbo',
  'Valparaíso',
  'Viña del Mar',
  'Santiago',
  'Puente Alto',
  'Rancagua',
  'Talca',
  'Chillán',
  'Concepción',
  'Los Ángeles',
  'Temuco',
  'Valdivia',
  'Puerto Montt',
  'Coyhaique',
  'Punta Arenas',
];
